### ISSUE TITLE
Received Content Creator badge & role before being accepted

### ISSUE THREAD

**Issue by naviisml** [everyday-as/gmodstore-issues#1024]
## Expected Behavior
This aint supposed to happen

## Actual Behavior
After submission, I received the badge 'Content Creator' without being accepted or denied.

## Steps to Reproduce the Problem

  1. Make a submission
  2. BOOM! Magic gives you the badge 
  3. Get denied and the badge goes away?

## Specifications

  - GmodStore version (see footer): v8.6.8 
  - Example url: https://www.gmodstore.com/market/create
  - Browser: Firefox
  - Event ID: NuN

**Comment by Marcuzz** [comment]
This happened due to an addon being accidentally accepted by a content curator.

I'll leave the issue open as the role should be taken away, the badge probably should not, though as it's not easy to determine whether a user has ever been a content creator. The badge's description is "Has been a Content Creator at some point", after all.

**Comment by Marcuzz** [comment]
This should now be fixed in the next release. We were not updating permission groups when an addon is denied.
