### ISSUE TITLE
Hide/Approved Reviews

### ISSUE THREAD

**Issue by nykez** [everyday-as/gmodstore-issues#1043]
## Describe a feature you would like to have added to GmodStore

Once a review is left on a script: Hide that review until the seller has time to approve it. This will allow the seller and customer to work out any blockers or concerns they may have had. This will also prevent people leaving bad reviews just to get better support or features.

After so many days if the creator has not responded to the review than it gets auto approved. 

## Related attachments

[https://i.imgur.com/oUTtsd5.png](https://i.imgur.com/oUTtsd5.png)

**Comment by TheodoorP** [comment]
Isn't #671 a better solution? Maybe with a check that ensures that if a creator reports a review within those 24 hours the review is only shown after that report has been handled, but that aside I would argue it's a better solution.

**Comment by nykez** [comment]
> 
> 
> Isn't #671 a better solution? Maybe with a check that ensures that if a creator reports a review within those 24 hours the review is only shown after that report has been handled, but that aside I would argue it's a better solution.

I don't see how this fixes the problem unfortunately. 24 hours is a insanely small response time for both a creator and the moderation team to handle a review. My issue is to give more control to the creator over their reviews (in the end their product rep), and have a direct line to first try to resolve the issue with the customer instead of the staff team. If no resolution could be made, either party could bring it up to the moderation team, while the review still remains hidden.

**Comment by TheodoorP** [comment]
I mentioned a fix for the moderation time to reply part in my previous reply. However, I don't think giving creators control over reviews will be a good idea. This will probably end up in a lot more reports from the customer towards the seller due to unreasonably "not accepting" reviews.

Just like on any platform, sellers should not have power over their own reviews. The 24-hour thing (+ time it takes the moderation team to make a decision) would give creators a chance to fight if they see necessary. If you think 24 hours is too little then we could also do 36, but that's not the main point here.
