### ISSUE TITLE
Addon license not linked on addon marketplace page

### ISSUE THREAD

**Issue by kanalumaddela** [everyday-as/gmodstore-issues#1044]
## Expected Behavior
- "License" link on a given addon's page to view the license agreement

## Actual Behavior
- There is no button/link on the page to view the addon's license agreement like for https://www.gmodstore.com/market/view/lsac-the-best-serverside-anti-cheat ,  even though it is publicly accessible via https://www.gmodstore.com/market/view/lsac-the-best-serverside-anti-cheat/license/kanalumaddela

## Steps to Reproduce the Problem

  1. https://www.gmodstore.com/market/view/lsac-the-best-serverside-anti-cheat
  2. Try to look for the addon License
  3. Fail
  4. Manually enter `https://www.gmodstore.com/market/view/lsac-the-best-serverside-anti-cheat/license/{username|steam64}` to view

## Specifications

  - GmodStore version (see footer): v8.7.15
  - Example url: https://www.gmodstore.com/market/view/lsac-the-best-serverside-anti-cheat
  - Browser: N/A
  - Event ID: N/A

**Comment by TheodoorP** [comment]
Pretty sure this is currently done on purpose, and the license is only linked once a user presses the purchase button. I would assume this may be done this way due to a user not actually caring about the license unless they want to purchase the item, however I'm not sure. 

@Marcuzz was this not showing the license on the addon page intentional?

**Comment by TheodoorP** [comment]
Just had confirmation that this is indeed intentional. The license is not relevant data for the addon page, and due to there already being so many things on the addon page it's best not to add even more additional content.

If however you've got a really good reason for showing the a link to the license on the addon page let us know :)
