### ISSUE TITLE
Ticket Signatures

### ISSUE THREAD

**Issue by LucaTanks** [everyday-as/gmodstore-issues#1067]
### Feature

I would like the ability to add a signature for tickets.  

### Additional Information

Adding signatures is an easy way for people to add nice messages, or maybe external contact info etc so people can show their GitHub etc or link their Discord. It can overall make creators sound more professional and gives possibilities to put banners and logos into the ticket.

**Comment by Marcuzz** [comment]
Because I feel like I easily forget stuff, the current plan is:

- Signatures will be global, and will be editable in your user settings. This means normal users can also make signatures.
- You will be able to use the same variables that also work in quick replies and normal tickets.

Moderators & curators in site tickets, reports, submissions and ban appeals will get a pre-defined global signature. This is so that they do not conflict with signatures they set for use with their addon tickets.

**Comment by LucaTanks** [comment]
Sounds good. I was thinking of some new variables that could help, but the only one I can remember at this moment is Team Name.

**Comment by Marcuzz** [comment]
![image](https://user-images.githubusercontent.com/3168421/127511864-7b7e5390-d85f-4aaf-87a8-1fc86ca9ee51.png)

Coming soon ™️

**Comment by Marcuzz** [comment]
This is now done. Combined with the new quick reply behaviour it's turning out really nicely:

https://user-images.githubusercontent.com/3168421/127520006-b364cbb2-421e-4877-8d50-37b6f4412373.mp4
