### ISSUE TITLE
Invalid reviews amount on product page

### ISSUE THREAD

**Issue by hugoheml** [everyday-as/gmodstore-issues#1243]
### Expected Behavior

The reviews amount must be the same as the sum of all reviews in all reviews pages

### Actual Behavior

The number does'nt correspond to it:

As we can see on the first screenshot, the product as 26 reviews
But in the last page, we have 4 reviews so 5 * 4 + 4 = 29 are visible, not 26.
![image](https://user-images.githubusercontent.com/51268820/215785894-e1d2b5be-f667-4e0f-8629-717ef2fcb4eb.png)
![image](https://user-images.githubusercontent.com/51268820/215786065-9070f450-e63c-4b2a-a708-0b9d5188c04c.png)

### Reproduction Steps

```markdown
1. Open a product page
```

### Browsers

Chrome/109.0.0.0 Safari/537.36

### Example URL

https://www.gmodstore.com/market/view/realistic-wood-cutter-the-most-advanced-wood-cutting-system

### GmodStore Version

v12.7.0

**Comment by TheodoorP** [comment]
I've looked into the described bug, and have come to the conclusion that this is mostly wanted behaviour. 

Two of the provided reviews were made by users that were given the addon for free, so that brings us to 28 reviews. As for the last remaining one, one of the reviews belongs to a user which had his purchase transferred to another account. This means we can't verify whether the user purchased the addon, or was given it for free. Thus we don't count it when calculating the rating.

The final user is somewhat of a bug, but not something we're interested in fixing. The other two users are intended not to be counted.
