### ISSUE TITLE
Navbar with Notice causes bad positioning

### ISSUE THREAD

**Issue by LivacoNew** [everyday-as/gmodstore-issues#1282]
### Expected Behavior

This new weird sticky navbar stays at the top along with notices

### Actual Behavior

This: https://upload.livaco.dev/u/JbO8pkg1FH.mp4

### Reproduction Steps

```markdown
1. Go onto the website while an notice is active
```

### Browsers

Firefox 118.0.2 (64-bit)

### Example URL

https://www.gmodstore.com/users/Livaco

### GmodStore Version

v16.0.4 

### Additional Information

Also please make the sticky navbar a toggle somewhere so I don't have it stalking me everywhere I go on the website

**Comment by Marcuzz** [comment]
This has now been fixed.

We will not be adding a toggle for the sticky behaviour, but we now hide the navbar along with the notices when you're scrolling downwards. They will reappear when you scroll upwards because you more often than not intend to navigate elsewhere when you're scrolling upwards.
