### ISSUE TITLE
Labels Broken

### ISSUE THREAD

**Issue by LivacoNew** [everyday-as/gmodstore-issues#925]
## Expected Behavior
The ability to create and modify labels on the go on a support ticket.

## Actual Behavior
https://upload.livaco.dev/u/Jbevy1HKkZ.mp4
Labels can't be accessed without a ticket that's open, they also can't be created and it looks to be a really bad system currently.

## Steps to Reproduce the Problem

  1. Be a export hackor and addon creator.
  2. Upload an addon to gmodstore.
  3. Get it denied 5 times.
  4. Finally get it accepted after getting in trouble with a backdoor in it.
  5. Get a ticket from a user with an issue with his config that you want to label "dumb"
  6. Realise you can't create any or manage them until you get a ticket.
  7. Cry.

## Specifications

  - GmodStore version (see footer); v7.1.23
  - Example url: https://www.gmodstore.com/dashboard/tickets/tags/devlogs-a-in-game-devlog-system-1/edit
  - Browser: Google Chrome
  - Event ID: N/A

**Comment by Marcuzz** [comment]
I've fixed ticket tag creation in 7.1.24, but I think we will wait with allowing creation and editing of labels without an existing ticket until an eventual re-design of the ticket system as on first glance it seems like a bigger change than expected due to tags belonging to a certain addon and the tickets area being global for all your addons.
